#!/usr/bin/env python3
"""
upload_youtube.py

Uploads a video file to YouTube using OAuth2.

First run on a new server: prompts you to visit a URL and paste back an auth
code. The token is saved to config/youtube_token.json and reused automatically.

Usage:
    python upload_youtube.py --file path/to/video.mp4 --title "My Video"
    python upload_youtube.py --file video.mp4 --title "My Video" --privacy public
"""

import argparse
import os
import sys
from pathlib import Path

from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError
from googleapiclient.http import MediaFileUpload

SCOPES = ["https://www.googleapis.com/auth/youtube.upload"]

APP_DIR = Path(os.environ.get("APP_DIR", "/opt/nhl-highlighter"))
CREDENTIALS_FILE = APP_DIR / "config" / "client_secrets.json"
TOKEN_FILE = APP_DIR / "config" / "youtube_token.json"


def get_authenticated_service():
    creds = None

    if TOKEN_FILE.exists():
        creds = Credentials.from_authorized_user_file(str(TOKEN_FILE), SCOPES)

    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            if not CREDENTIALS_FILE.exists():
                print(f"ERROR: OAuth credentials file not found: {CREDENTIALS_FILE}")
                print()
                print("To create one:")
                print("  1. Go to console.cloud.google.com")
                print("  2. APIs & Services → Credentials → Create Credentials → OAuth client ID")
                print("  3. Application type: Desktop app")
                print("  4. Download JSON and upload to the server:")
                print(f"     scp client_secrets.json root@SERVER:{CREDENTIALS_FILE}")
                sys.exit(1)

            # run_console() is headless-safe: prints a URL and reads a pasted code.
            flow = InstalledAppFlow.from_client_secrets_file(str(CREDENTIALS_FILE), SCOPES)
            creds = flow.run_console()

        TOKEN_FILE.parent.mkdir(parents=True, exist_ok=True)
        TOKEN_FILE.write_text(creds.to_json())
        TOKEN_FILE.chmod(0o600)
        print(f"Token saved to {TOKEN_FILE}")

    return build("youtube", "v3", credentials=creds)


def upload_video(
    file_path: Path,
    title: str,
    description: str = "Generated by NHL Highlighter",
    privacy: str = "unlisted",
) -> str:
    youtube = get_authenticated_service()

    body = {
        "snippet": {
            "title": title,
            "description": description,
            "categoryId": "20",  # Gaming
        },
        "status": {
            "privacyStatus": privacy,
        },
    }

    media = MediaFileUpload(str(file_path), chunksize=10 * 1024 * 1024, resumable=True)
    request = youtube.videos().insert(part="snippet,status", body=body, media_body=media)

    print(f"Uploading: {file_path.name}  ({file_path.stat().st_size // 1_000_000} MB)")
    response = None
    while response is None:
        status, response = request.next_chunk()
        if status:
            print(f"  {int(status.progress() * 100)}%", end="\r", flush=True)

    video_id = response["id"]
    print(f"\nUpload complete! https://www.youtube.com/watch?v={video_id}")
    return video_id


def main():
    parser = argparse.ArgumentParser(description="Upload a video to YouTube")
    parser.add_argument("--file", required=True, help="Path to video file")
    parser.add_argument("--title", required=True, help="Video title")
    parser.add_argument(
        "--description",
        default="Generated by NHL Highlighter",
        help="Video description",
    )
    parser.add_argument(
        "--privacy",
        default="unlisted",
        choices=["public", "unlisted", "private"],
    )
    args = parser.parse_args()

    file_path = Path(args.file)
    if not file_path.exists():
        print(f"ERROR: File not found: {file_path}")
        sys.exit(1)

    try:
        upload_video(file_path, args.title, args.description, args.privacy)
    except HttpError as exc:
        print(f"YouTube API error: {exc}")
        sys.exit(1)


if __name__ == "__main__":
    main()
